#워크플로 이름. CI를 실행하기 위한 스크립트 모음이므로 CI로 지정
name : CI

#워크플로가 시작될 조건 지정. main 브랜치에 푸시할 때마다 워크 플로 시작
on :
  push :
    branches : [main]

jobs :
  build :
    runs-on : ubuntu-latest #실행 환경 지정. 리눅스, 윈도우 등
    #실행 스텝 지정
    steps :
      #uses : 지정한 리포지토리를 확인하고 코드에 대한 작업을 실행할 수 있음
      - uses: actions/checkout@v3 #checkout이라는 작업의 v3버전을 실행

      - uses: actions/setup-java@v3 #setup-java라는 작업의 v3버전을 실행
        with :
          distribution : 'zulu'
          java-version : '17'
        #name: 스텝의 이름을 지정
      - name : Grant execute permission for gradlew
        #run : 실행할 명령어를 입력
        run : chmod +x gradlew

      - name : Build with Gradle
        run : ./gradlew clean build #그레들을 사용해 프로젝트를 빌드 이전 상태로 돌리고 다시 빌드하는 명령어 실행